start_time: 0.0
end_time: 600.0
supply_price_low: 95
supply_price_high: 95
demand_price_low: 105
demand_price_high: 105
interval: 30
timemode: 'drip-poisson'
buyers_spec:
            GVWY: 20
            SHVR: 20 
            ZIC: 20
            ZIP: 20
sellers_spec:
        GVWY: 20
        SHVR: 20 
        ZIC: 20
        ZIP: 20
n_trials: 1
trade_file: 'avg_balance.csv'
trial: 1
verbose: False
